# Generated by Django 6.0.2 on 2026-02-25 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Build', max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usecase', models.CharField(default='Gaming', max_length=80)),
                ('build_data', models.JSONField(default=list)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
